// =============================================================================
// CHROMODYNAMIC — cd/cluster_pbr/Lookup.hpp
// Phase 10 / Wave 105 — Forward+ PBR fragment-shader integration.
//
// Closes Phase 8 routing item #1 (PBR Forward+ shader integration) on
// the DESIGN side: ships the GLSL helper a PBR fragment shader
// #include's to iterate only the lights in its cluster, plus a C++
// struct documenting the descriptor-set layout the host-side material
// pipeline must wire up.
//
// Why an interface library: the integration is a contract between
// (1) the host-side material/pipeline (binds the cluster buffers
// from cd::cluster_gpu) and (2) the fragment shader (reads them).
// The contract is enforced at the GLSL `#include` boundary; no
// compiled C++ is needed.
//
// Material-side wiring (sketch):
//   set 0 (existing)  — camera / material uniforms
//   set 1 (existing)  — base color / normal / ORM textures
//   set 2 (NEW)       — cluster cluster_offsets + light_indices
//                       + lights ssbo (from cd::cluster_gpu)
//
// Fragment-shader-side usage:
//   #include "<cluster_pbr_lookup.glsl>"   // text from
//                                           // cluster_lookup_glsl()
//   ...
//   uint cluster_id = cluster_lookup_id(view_pos, ...);
//   uvec2 range = cluster_lookup_light_range(cluster_id);
//   for (uint k = range.x; k < range.y; ++k) {
//       uint light_id = u_light_indices.indices[k];
//       LightData L = u_lights.lights[light_id];
//       // ... PBR direct-light eval ...
//   }
//
// The actual fragment shader sticks PBR-domain code around this loop;
// the cluster lookup itself is mechanical and shared across every
// Forward+ material.
// =============================================================================
#pragma once

#include <cstdint>
#include <string_view>

namespace cd::cluster_pbr
{

/// Descriptor-set layout the Forward+ material must allocate.
/// Mirrors cd::cluster_gpu's pipeline binding shape so the buffers
/// cd::cluster_gpu writes are read by the PBR fragment shader
/// without reshuffling.
struct DescriptorBindings
{
    /// Storage-buffer binding for the lights array (mirror of
    /// cluster_assign.comp's binding 0).
    static constexpr std::uint32_t kLightsBinding = 0U;
    /// Storage-buffer binding for cluster_offsets[X·Y·Z + 1] (read-only).
    static constexpr std::uint32_t kClusterOffsetsBinding = 1U;
    /// Storage-buffer binding for light_indices[total] (read-only).
    static constexpr std::uint32_t kLightIndicesBinding = 2U;
};

/// Push-constant struct passed alongside the camera matrices so the
/// fragment shader can reconstruct cluster ID from gl_FragCoord. The
/// fields match the cluster_assign.comp push constants for layout
/// parity.
struct LookupPushConstants
{
    std::uint32_t cells_x;
    std::uint32_t cells_y;
    std::uint32_t cells_z;
    float near_plane;
    float far_plane;
    float fov_y_rad;
    float aspect;
    std::uint32_t pad;  // 32-byte aligned
};
static_assert(sizeof(LookupPushConstants) == 32,
              "Forward+ PBR push-constant block must be 32 bytes");

/// The GLSL helper. Host-side glslang invocations prepend this string
/// to the fragment shader source before compile (or use it as a
/// virtual `#include` if the toolchain supports it).
///
/// Functions exposed:
///   uint cluster_lookup_id(vec3 view_pos)        — view-space → cluster id
///   uvec2 cluster_lookup_light_range(uint cid)    — (begin, end) into light_indices
///   uint cluster_lookup_light_count()              — total in-cluster light count
///
/// The host-side pipeline must bind:
///   set = CLUSTER_PBR_SET  binding 0 : InLights        (read-only SSBO)
///                          binding 1 : ClusterOffsets  (read-only SSBO)
///                          binding 2 : LightIndices    (read-only SSBO)
/// `CLUSTER_PBR_SET` is a GLSL preprocessor symbol the caller can
/// override (default 2; see ADR-20260523-wave105 for layout).
[[nodiscard]] inline std::string_view cluster_lookup_glsl() noexcept
{
    return R"GLSL(
// -----------------------------------------------------------------------------
// cluster_pbr_lookup.glsl — generated by cd::cluster_pbr::cluster_lookup_glsl
// -----------------------------------------------------------------------------
#ifndef CLUSTER_PBR_SET
#define CLUSTER_PBR_SET 2
#endif

struct ClusterPbrLight {
    vec4 position_radius;  // matches cluster_assign.comp LightData
};

layout(set = CLUSTER_PBR_SET, binding = 0, std430) readonly buffer ClusterPbrInLights {
    uint  light_count;
    uint  pad_0;
    uint  pad_1;
    uint  pad_2;
    ClusterPbrLight lights[];
} u_cluster_pbr_lights;

layout(set = CLUSTER_PBR_SET, binding = 1, std430) readonly buffer ClusterPbrOffsets {
    uint offsets[];
} u_cluster_pbr_offsets;

layout(set = CLUSTER_PBR_SET, binding = 2, std430) readonly buffer ClusterPbrIndices {
    uint indices[];
} u_cluster_pbr_indices;

layout(push_constant) uniform ClusterPbrPC {
    uint  cells_x;
    uint  cells_y;
    uint  cells_z;
    float near_plane;
    float far_plane;
    float fov_y_rad;
    float aspect;
    uint  pad;
} u_cluster_pbr_pc;

uint cluster_pbr_depth_z(float depth) {
    float clamped = clamp(depth, u_cluster_pbr_pc.near_plane,
                          u_cluster_pbr_pc.far_plane);
    float t = log(clamped / u_cluster_pbr_pc.near_plane)
            / log(u_cluster_pbr_pc.far_plane / u_cluster_pbr_pc.near_plane);
    return min(uint(floor(t * float(u_cluster_pbr_pc.cells_z))),
               u_cluster_pbr_pc.cells_z - 1u);
}

uint cluster_pbr_xy(float angle, float tan_half, uint cells) {
    float t = clamp(tan(angle) / tan_half, -1.0, 1.0);
    float u = (t + 1.0) * 0.5 * float(cells);
    return uint(clamp(floor(u), 0.0, float(cells - 1u)));
}

uint cluster_lookup_id(vec3 view_pos) {
    float depth = -view_pos.z;
    uint cz = cluster_pbr_depth_z(depth);
    float depth_for_angle = max(depth, 1.0e-3);
    float angle_x = atan(view_pos.x, depth_for_angle);
    float angle_y = atan(view_pos.y, depth_for_angle);
    float half_fov_y = u_cluster_pbr_pc.fov_y_rad * 0.5;
    float tan_half_y = tan(half_fov_y);
    float tan_half_x = u_cluster_pbr_pc.aspect * tan_half_y;
    uint cx = cluster_pbr_xy(angle_x, tan_half_x, u_cluster_pbr_pc.cells_x);
    uint cy = cluster_pbr_xy(angle_y, tan_half_y, u_cluster_pbr_pc.cells_y);
    return (cz * u_cluster_pbr_pc.cells_y + cy) * u_cluster_pbr_pc.cells_x + cx;
}

uvec2 cluster_lookup_light_range(uint cluster_id) {
    return uvec2(u_cluster_pbr_offsets.offsets[cluster_id],
                 u_cluster_pbr_offsets.offsets[cluster_id + 1u]);
}

uint cluster_lookup_light_count() {
    return u_cluster_pbr_lights.light_count;
}
)GLSL";
}

}  // namespace cd::cluster_pbr
